# !/usr/bin/env python

import ctypes
import numpy as np

from pyscf.fci import direct_spin1

from mrh.lib.helper import load_library
from mrh.my_pyscf.pbc.fci.direct_spin1_cplx import _unpack

# Author: Bhavnesh Jangid

libcplxcsf = load_library("libcplx_csf")

def sanity_check_link_index_without_trilidx(link_index, norb):
    '''
    Check that the link_index table is an ordinary orbital-index table, not a
    tril-index table.  The latter is incompatible with the native kernel below.
    '''
    link_index = np.asarray(link_index)
    if link_index.ndim != 3 or link_index.shape[2] != 4:
        msg = "Not a valid link_index table; expected shape (nstr, nlink, 4)"
        raise ValueError(msg)
    
    # In an ordinary link table, columns 0 and 1 are creation and destruction
    # orbital indices.  A tril-index table stores a packed pair index in column
    # 0 and is incompatible with the native kernel below.
    orbital_indices = link_index[..., :2]
    if np.any(orbital_indices < 0) or np.any(orbital_indices >= norb):
        msg = "Not a valid link_index table; " \
        "orbital indices must be in [0, norb)"
        raise ValueError(msg)

    return np.ascontiguousarray(link_index, dtype=np.int32)

def _transform_complex_ci(transformer, civec, transform, ncoeff,
                          order='C', normalize=True, return_norm=False):
    '''
    Apply a real CSF transformation to a complex CI vector in one call.
    The real and imaginary parts are stacked as independent real vectors.  The
    underlying transformer therefore constructs and applies each real CSF
    transformation matrix only once for both parts.
    '''
    is_list = isinstance(civec, list)
    is_tuple = isinstance(civec, tuple)
    civec = np.asarray(civec)
    if civec.size % ncoeff:
        msg = f"CI vector has {civec.size} elements; expected a multiple of {ncoeff}"
        raise ValueError(msg)

    nvec = civec.size // ncoeff
    is_flat = civec.ndim == 1 and not (is_list or is_tuple)
    if order.upper() == 'F':
        civec = civec.reshape(ncoeff, nvec).T
    else:
        civec = civec.reshape(nvec, ncoeff)

    civec_ri = np.ascontiguousarray(np.concatenate((civec.real, civec.imag), 
                                                   axis=0))
    transformed_ri = transform(civec_ri, order='C', normalize=False)
    transformed_ri = np.asarray(transformed_ri).reshape(2*nvec, -1)
    transformed = (transformed_ri[:nvec].astype(np.complex128)
        + 1j * transformed_ri[nvec:])

    norms = np.linalg.norm(transformed, axis=1)
    if normalize:
        nonzero = ~np.isclose(norms, 0)
        # Avoid division by zero for zero-norm vectors
        transformed[nonzero] /= norms[nonzero, np.newaxis]

    if order.upper() == 'F': transformed = transformed.T
    if is_flat: transformed = transformed.ravel()
    elif is_list: transformed = list(transformed)
    elif is_tuple: transformed = tuple(transformed)

    if norms.size == 1: norms = norms[0]
    if return_norm: return transformed, norms
    return transformed

def vec_det2csf_cplx(transformer, civec, order='C',
                     normalize=True, return_norm=False):
    '''
    Transform complex determinant coefficients to CSFs in one call.
    '''
    return _transform_complex_ci(
        transformer, civec, transformer.vec_det2csf, transformer.ndet,
        order=order, normalize=normalize, return_norm=return_norm,)

def vec_csf2det_cplx(transformer, civec, order='C',
                     normalize=True, return_norm=False):
    '''
    Transform complex CSF coefficients to determinants in one call.
    '''
    return _transform_complex_ci(
        transformer, civec, transformer.vec_csf2det, transformer.ncsf,
        order=order, normalize=normalize, return_norm=return_norm,
    )

def contract_1e(h1e, fcivec, norb, nelec, link_index=None):
    '''
    Contract a complex spin-separated one-electron Hamiltonian.
    args:
        h1e: np.ndarray of shape (2, norb, norb) 
            spin-separated one-electron Hamiltonian.
        fcivec: np.array of shape (nalpha, nbeta) or (nalpha*nbeta,) 
            CI vector
        norb: int
            active space orbitals
        nelec: tuple of int 
            number of electrons (nalpha, nbeta)
        link_index: Ordinary alpha/beta link tables generated by
            :func:`pyscf.fci.cistring.gen_linkstr_index`.
            without tril-indexing.  If None, the link tables are generated automatically.
    '''

    h1e = np.asarray(h1e)
    if h1e.shape != (2, norb, norb):
        msg = f"h1e must have shape (2, {norb}, {norb}); got {h1e.shape}"
        raise ValueError(msg)

    link_indexa, link_indexb = _unpack(norb, nelec, link_index)

    # Sanity check the link_index tables
    link_indexa = sanity_check_link_index_without_trilidx(link_indexa, norb)
    link_indexb = sanity_check_link_index_without_trilidx(link_indexb, norb)

    na, nlinka = link_indexa.shape[:2]
    nb, nlinkb = link_indexb.shape[:2]

    fcivec = np.asarray(fcivec)
    if fcivec.size != na * nb:
        msg = f"fcivec has {fcivec.size} elements; expected {na * nb}"
        raise ValueError(msg)

    h1e = np.ascontiguousarray(h1e, dtype=np.complex128)
    fcivec = np.ascontiguousarray(fcivec, dtype=np.complex128)
    ci1 = np.empty_like(fcivec)

    # Call the C function to perform the contraction
    # Currently, I have written a combined C function for both alpha and beta contractions. 
    # TODO: In future, I will write separate C functions for more modularity and clarity.

    libcplxcsf.FCIcontract_uhf_1e_cplx(
        h1e[0].ctypes.data_as(ctypes.c_void_p),
        h1e[1].ctypes.data_as(ctypes.c_void_p),
        fcivec.ctypes.data_as(ctypes.c_void_p),
        ci1.ctypes.data_as(ctypes.c_void_p),
        ctypes.c_int(norb),
        ctypes.c_int(na),
        ctypes.c_int(nb),
        ctypes.c_int(nlinka),
        ctypes.c_int(nlinkb),
        link_indexa.ctypes.data_as(ctypes.c_void_p),
        link_indexb.ctypes.data_as(ctypes.c_void_p),
    )
    return ci1.reshape(fcivec.shape).view(direct_spin1.FCIvector)
