/*
 * Complex, spin-separated one-electron FCI contraction.
 *
 * Unlike pyscf.fci.direct_uhf.contract_1e, this kernel consumes the ordinary
 * four-column link table generated by cistring.gen_linkstr_index:
 *
 *     (creation orbital, destruction orbital, target address, sign)
 *
 * No packed-triangular orbital-pair index is used, so the alpha and beta
 * Hamiltonians may be general complex matrices.
 */

 /* 
 * Author: Bhavnesh Jangid
 */

#include <complex.h>
#include <stddef.h>
#include <stdlib.h>
#include <omp.h>
#include "fci.h"


void FCIcontract_uhf_1e_cplx(double complex *h1e_a,
                             double complex *h1e_b,
                             double complex *ci0,
                             double complex *ci1,
                             int norb, int na, int nb,
                             int nlinka, int nlinkb,
                             int *link_indexa,
                             int *link_indexb)
{
        size_t idet;
        int stra, strb, j;
        const size_t ndet = ((size_t)na) * nb;
        _LinkT *clink_indexa = malloc(sizeof(_LinkT) * ((size_t)na) * nlinka);
        _LinkT *clink_indexb = malloc(sizeof(_LinkT) * ((size_t)nb) * nlinkb);

        FCIcompress_link(clink_indexa, link_indexa, norb, na, nlinka);
        FCIcompress_link(clink_indexb, link_indexb, norb, nb, nlinkb);

#pragma omp parallel for schedule(static)
        for (idet = 0; idet < ndet; idet++) {
                ci1[idet] = 0.0 + 0.0 * I;
        }

/*
 * Parallelize the alpha contraction over beta strings.  Each thread owns a
 * complete CI-vector column, so different source strings can safely scatter
 * into their linked alpha target strings without atomic updates.
 */
#pragma omp parallel for private(stra,j) schedule(static)
        for (strb = 0; strb < nb; strb++) {
                for (stra = 0; stra < na; stra++) {
                        const double complex c = ci0[((size_t)stra) * nb + strb];
                        const _LinkT *tab = clink_indexa + ((size_t)stra) * nlinka;

                        for (j = 0; j < nlinka; j++) {
                                const int a = EXTRACT_CRE(tab[j]);
                                const int i = EXTRACT_DES(tab[j]);
                                const int str1 = EXTRACT_ADDR(tab[j]);
                                const int sign = EXTRACT_SIGN(tab[j]);

                                ci1[((size_t)str1) * nb + strb] +=
                                        sign * h1e_a[((size_t)a) * norb + i] * c;
                        }
                }
        }

/*
 * Parallelize the beta contraction over alpha strings.  Each thread owns a
 * complete CI-vector row and can safely scatter among beta target strings.
 */
#pragma omp parallel for private(strb,j) schedule(static)
        for (stra = 0; stra < na; stra++) {
                for (strb = 0; strb < nb; strb++) {
                        const double complex c = ci0[((size_t)stra) * nb + strb];
                        const _LinkT *tab = clink_indexb + ((size_t)strb) * nlinkb;

                        for (j = 0; j < nlinkb; j++) {
                                const int a = EXTRACT_CRE(tab[j]);
                                const int i = EXTRACT_DES(tab[j]);
                                const int str1 = EXTRACT_ADDR(tab[j]);
                                const int sign = EXTRACT_SIGN(tab[j]);

                                ci1[((size_t)stra) * nb + str1] +=
                                        sign * h1e_b[((size_t)a) * norb + i] * c;
                        }
                }
        }

        free(clink_indexb);
        free(clink_indexa);
}
